In [1]:
from numpy import *

In [3]:
num_movies=10

In [4]:
num_users=5

In [5]:
ratings = random.randint(11, size = (num_movies, num_users))

In [7]:
print (ratings)

[[7 7 6 2 4]
 [5 0 5 1 3]
 [0 4 3 4 0]
 [5 2 8 6 3]
 [2 3 7 7 9]
 [6 9 6 8 6]
 [0 9 3 1 6]
 [3 3 2 3 8]
 [9 9 4 1 5]
 [4 9 6 1 0]]


In [8]:
did_rate = (ratings!=0)*1

In [9]:
print (did_rate)

[[1 1 1 1 1]
 [1 0 1 1 1]
 [0 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 0]]


In [10]:
print (ratings!=0)

[[ True  True  True  True  True]
 [ True False  True  True  True]
 [False  True  True  True False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True False]]


In [14]:
print (ratings !=0) * 1

[[ True  True  True  True  True]
 [ True False  True  True  True]
 [False  True  True  True False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True False]]


TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

In [15]:
ratings.shape

(10, 5)

In [17]:
did_rate.shape

(10, 5)

In [19]:
nikhil_ratings = zeros((num_movies, 1))
print (nikhil_ratings)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [24]:
print (nikhil_ratings)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [25]:
nikhil_ratings[0] = 8
nikhil_ratings[4] = 7
nikhil_ratings[7] = 3

In [26]:
print (nikhil_ratings)

[[8.]
 [0.]
 [0.]
 [0.]
 [7.]
 [0.]
 [0.]
 [3.]
 [0.]
 [0.]]
